if [ "$PS1" ]; then
    PS1='[\W]\$ '
    alias ll='ls -lhaG'
    alias lm='ls -1G'
    alias screen='screen -U -D -RR'
    if tty -s; then
        stty stop undef
        stty start undef
        stty -ixon  # for os x
    fi
    export HISTSIZE=50000
    export HISTCONTROL=ignoreboth
    export HISTIGNORE="exit:screen:[bf]g:cd:history:history *"
    export IGNOREEOF=10

    # for history sharing over multiple shells
    function share_history {
        history -a
        history -c
        history -r
    }
    PROMPT_COMMAND='share_history'
    shopt -u histappend
fi

# adding git branch/status in prompt
# brew install bash-git-prompt
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  GIT_PROMPT_ONLY_IN_REPO=1
  GIT_PROMPT_THEME=Solarized
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi

export EDITOR=vim

# perl
export PERL5LIB=/usr/local/Cellar/perl/5.20.1/lib/5.20.1:$PERL5LIB
export PATH=/usr/local/Cellar/perl/5.20.1/bin:$PATH

# rbenv
eval "$(rbenv init -)"

# nodenv
export PATH="$HOME/.nodenv/bin:$PATH"
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

# npm
export PATH="./node_modules/.bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi

# go
export GOPATH=$HOME/workspace/go

# google cloud sdk
export PATH="$HOME/.google-cloud-sdk/bin:$PATH"

# Kaizen
export RAILS_ENV="development"
export BE="bundle exec"
function kzssh {
  ec2ls | percol | cut -f 6 | pbcopy && ssh iandeth@`pbpaste`
}

# for curl with user-agent iphone
export UA_SP="Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5"

# for ec2list
source ~/.aws

# for karma
source ~/.browserstack

# support github
export C=$HOME/workspace/cse
export CD=$HOME/workspace/cse-docs
